config/routes.rb
Rails.application.routes.draw do
  resources :categories do
  resources :products, only: [:create, :show, :edit, :destroy]
  end
  
  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @product = @category.products.build
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    if @product.save
      redirect_to category_path(@product.category_id)
    else
      redirect_to category_path(params[:category_id])
    end
  end

  def edit
    @product = Product.find(params[:id])
    @category = @product.category 
  end

  def new
    @product = Product.new
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    redirect_to category_path(@product.category_id)
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class: 'btn btn-success' %> |
<%= link_to 'Back', categories_path, class: 'btn btn-primary' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', category, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'Nueva Categoría', new_category_path %></h4>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


  <h4>Nombre:</h4>
  <%= @category.name %>

<%= form_with(model: [ @category, @product], local: true ) do |form| %>
<%= form.label :name, 'Ingresar nombre del producto:' %>
<%= form.text_field :name , class: 'form-group' %>

<%= form.label :price, 'Ingresar precio:' %>
<%= form.number_field :price %>

<%= form.submit 'Crear' , class: 'btn btn-success'%>
<% end %>



<table class="table">
  <tr>
    <th>Nombre </th>
    <th>Precio</th>
  </tr>

    <% @category.products.each do |product| %>
<% if product.id %>
    <tr>
      <td> <%= product.name %> </td>
      <td> <%= product.price %> </td>
      <td>
    <div class="btn btn-danger">
      <%= link_to 'X',  category_product_path(@category, product),  method: :delete  %>
    </div>
      </td>
      <td>
        <div class="btn btn-primary">
      <%= link_to 'Edit',  edit_category_product_path(@category, product) %>
    </div>
      </td>
    </tr>
    <% end %>
    <% end %>
 </table>

  <%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud Anidado</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-h21C2fcDk/eFsW9sC9h0dhokq5pDinLNklTKoxIZRUn3+hvmgQSffLLQ4G4l2eEr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>